### ISSUE TITLE
RSA鍵のデフォルトの鍵長が0になる

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#16]
SSH鍵生成ダイアログを開いた時にデフォルトで選択されている鍵の種類がED25519だが、
そこから鍵の種類をRSA(またはRSA1)に変更するとビット数が0となる。

## バージョン
5.0-RC2で発生。
4.107-RC3では問題なし (デフォルトがRSA)

**Comment by nmaya** [comment]
ありがとうございます。r10954 で修正しました。
