### ISSUE TITLE
SCP時に標準エラー出力への出力が有るとSCPが行えない

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#17]
SCP時、サーバー側でscpコマンドを起動した時にシェル等が標準エラー出力に何らかのメッセージを出力すると、ttssh側でエラーとなってSCPが終了する。

## 再現手順
サーバー側のログインシェルがbashの場合は`~/.bashrc`に、zshの場合は`~/.zshenv`に以下の記述を追加する。
```
echo message >&2
```
この状態でSCP送信、またはSCP受信を行うと、`message`という内容のエラーダイアログが出てSCPが行えない。
同じ環境でOpenSSHのscpクライアントの場合は`message`と表示されるがSCPはそのまま行える。

## バージョン
以下で再現。
 * 4.106
 * 4.107-RC3
 * 5.0-RC2

## 備考
zshの場合、`~/.zshenv`には通常はメッセージ出力するようなコマンドは入れないので問題になる事はほぼ無い。

bashの場合、`~/.bashrc`は本来はインタラクティブシェル用の設定ファイルで有る為、メッセージ出力をするコマンドが入れられる事が有る。他にも`stty`等の端末が割り当てられている事が必要なコマンドが入れられる事が有ある。
しかし、bashでは標準入力がネットワークに繋がっている場合は非インタラクティブシェルでも`~/.bashrc`を実行するという腐った仕様が有る為、scpコマンド起動時に`~/.bashrc`が実行されてメッセージが出力されたり、端末が割り当てられていないというエラーメッセージが出力される事がある。

## 原因
SCP時でもSSH_MSG_CHANNEL_EXTENDED_DATAをSSH_MSG_CHANNEL_DATAと同じように扱っている為。

## 対応案
SCP時のSSH_MSG_CHANNEL_EXTENDED_DATAの扱いを変更する。
 * 何もせず無視する
 * ダイアログを表示する
 * VTウィンドウに出力する
 * デバッグログに出力する

### tasklist
- [ ] この表示方法でよいか確認中
- trunk
  - [x] 修正 r10970
  - [x] 変更履歴 r10970, r10976
- 4-stable
  - [x] 修正 r10971
  - [x] 変更履歴 r10971, r10977

**Comment by ttdoda** [comment]
* 何も表示しないのは、scpコマンドの起動が失敗した時に分かりづらい
 * VTウィンドウに出力するのは紛らわしい
 * デバッグログへの出力もエラー時に分かりづらい

という辺りから、ダイアログを表示するのが無難か。出力が有った時に毎回出るのはうざいかもしれないが。

**Comment by nmaya** [comment]
- ~~ポップアップメッセージ~~通知バルーン（今はトーストでしたっけ？）を表示する
も選択肢になりますか？

**Comment by nmaya** [comment]
このようにすることで通知バルーンで表示されました。

```
	} else if (c->type == TYPE_SCP) {  // SCP
		char *msg = (char *)malloc(strlen+1);
		wchar_t *msgW;
		memcpy(msg, data, strlen);
		msg[strlen] = '\0';
		msgW = ToWcharU8(msg);
		if (msgW) {
			NotifySetIconID(pvar->cv, hInst, pvar->settings.IconID);
			NotifyWarnMessageW(pvar->cv, msgW, L"SSH_MSG_CHANNEL_EXTENDED_DATA");
			NotifySetIconID(pvar->cv, NULL, 0);
			free(msgW);
		}
		free(msg);
```

タイトルは "SSH_MSG_CHANNEL_EXTENDED_DATA" としています。
標準エラー出力は SSH_MSG_CHANNEL_EXTENDED_DATA で飛んできますが、標準エラー出力でない何かを SSH_MSG_CHANNEL_EXTENDED_DATA に乗せて飛ばしてくるかもしれないので、プロトコルまんまのこのタイトルでいいかなと思っています。
意見がなければこのままコミットします。

**Comment by nmaya** [comment]
trunk（r10970）・4-stable（r10971）ともコミットしました。

**Comment by zmatsuo** [comment]
動作チェックしました。

trunk
r10970 でバルーン通知が出る
r10957 でダイアログがでる(ok押下で受信は継続できる)

4-stable
r10971 でバルーン通知が出る
r10956 でダイアログがでる(ok押下で受信は継続できる)

私のテスト環境では、ダイアログのokを押すと送受できました。
![#17_1009](https://github.com/TeraTermProject/osdn-download/assets/6488847/37bba192-b133-4fad-b98e-14125923c089)

**Comment by nmaya** [comment]
r10976, r10977 で変更履歴を修正しました。

**Comment by nmaya** [comment]
返信がないので close します。
なにかあったら https://github.com/TeraTermProject/teraterm/issues に再オープンしてください。
