### ISSUE TITLE
Rekey中の送信データが欠ける

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#18]
> * Rekey 中のパケット ... 保留にならず破棄されている（ソース中のコメントより）

https://github.com/TeraTermProject/osdn-download/issues/8#issuecomment-1722647644 で書いた別の原因で落ちるというのがおそらくこれが原因ですね。データが欠けてRDPサーバー側で復号出来なくなって切られていると思います。
あと、SCP送信でデータが欠けます。これはRekeyLimitを変える事によって簡単に再現できると思います。
普通の使い方だとあまり踏まないと思いますが、別Issueを立てて対応した方がいいかもしれません。

_Originally posted by @ttdoda in https://github.com/TeraTermProject/osdn-download/issues/8#issuecomment-1742668960_

### tasklist
- SSH_MSG_CHANNEL_DATA
  - trunk
    - [x] 修正 r10957
      - [ ] この対応でRDP接続が切れなくなったか確認中
    - [x] 変更履歴 r10968
  - 4-stable
    - [x] 修正 r10969
    - [x] 変更履歴 r10969
- SSH_MSG_CHANNEL_OPEN
- SSH_MSG_CHANNEL_INPUT_EOF

**Comment by ttdoda** [comment]
データ(パケット)の破棄を行っているのは以下の3か所。
 * SSH2_send_channel_data()
 * SSH2_channel_input_eof()
 * SSH_open_channel()

この内、実データが欠ける原因になっているのは SSH2_send_channel_data()。

他の二つはタイミングがシビアなためほぼ起こらないし、起きてもデータ欠けにはならない。
影響はチャネルの開始/終了が行われないという形で出るはず。

SSH2_send_channel_data() に関しては、フロー制御で送れなかった時と同じようにssh2_channel_add_bufchain()を呼べばよさそう。

**Comment by nmaya** [comment]
r10957 で修正しました。コード的に問題なさそうでしょうか？
手元では、shell でキーを押しっぱなしにしていて Rekey が発生したら echo が止まるのですが、Rekey が終わったらまとめて表示されています。
このバイナリでの動作はどうでしょうか？
https://ci.appveyor.com/project/teraterm/trunk-vs2022/builds/48197934/artifacts

**Comment by nmaya** [comment]
4-stable にもコミットしました。

**Comment by nmaya** [comment]
問題ないようなので close します。
なにかあったら https://github.com/TeraTermProject/teraterm/issues に再オープンしてください。
