### ISSUE TITLE
ウィンドウタイトルの初期状態がおかしい

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#2]
「設定」-「その他の設定」-「制御シーケンス」にある「ウィンドウタイトルの変更要求を受け入れる」の設定が"上書き"の状態でホストに接続した時、ウィンドウタイトルが「設定」-「ウィンドウ」の「タイトル」の設定が使われずに - となる。
この時、`echo -e "\e]0;title\a"` を実行するとウィンドウタイトルが期待通り`title`に変更される。
しかし「コントロール」-「リモートタイトルリセット」を実行すると - に戻る。

## バージョン
5.0 RC で再現。
5.0 Beta, 4.107 RC2では問題なし。

**Comment by zmatsuo** [comment]
r10935で修正しました。

**Comment by nmaya** [comment]
修正されたことを確認しました。
