### ISSUE TITLE
INI で指定したファイル名の相対パス/フルパスの扱い

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/osdn-download#20]
### UILanguageFile
UILanguageFile に相対パスを書くと、exe の位置からの相対パスとして扱われる（4/5共通だと思う）。

一方 UILanguageFile にフルパスを書くと、フルパスとして扱われてほしいのだが、exe の位置からの相対パスとして扱われる（5のみ。4は大丈夫だと思うが、念のため確認していただけると助かる）。

![UILanguageFile](https://github.com/TeraTermProject/osdn-download/assets/5668936/b0ecc738-4196-4ba2-a432-a4768b1f07b0)

UILanguageFile については、わざわざ変更することは少ないと思うので、大きな問題になることはないかもしれません。

### UILanguageFile 以外への展開
TERATERM.INI には、ほかにもファイルを指定する項目があります。

- 相対パスのときに「どこから」とみなされるのがふさわしいか
- 相対パスのとき、実際はどうか
- フルパスのとき、実際はどうか

というのが心配になってきます。

- UILanguageFile
  - expected: 自分で編集するようなファイルではないので exe の位置からの相対パス
- BGThemeFile
  - expected: 自分で編集することのあるファイルなので「設定ファイルのフォルダ」からの相対パス？
- ConfirmChangePasteStringFile
  - expected: 自分で編集することのあるファイルなので「設定ファイルのフォルダ」からの相対パス？
- KnownHostsFiles
  - expected: 自分で編集することのあるファイルなので「設定ファイルのフォルダ」からの相対パス
- DefaultRhostsHostPrivateKeyFile
  - expected: 自分で編集することのあるファイルなので「設定ファイルのフォルダ」からの相対パス？
- DefaultRSAPrivateKeyFile
  - expected: 自分で編集することのあるファイルなので「設定ファイルのフォルダ」からの相対パス？
- ほかにもファイルのパスが書けそうな項目がありますか？

**Comment by zmatsuo** [comment]
r10980 で TERATERM.INI の UILanguageFile で絶対パス指定できるようにしました。

Tera Term 4 では絶対パス指定可能でした。

Tera Term 4 の相対パス指定のとき、
カレントフォルダからの相対パスになっています。
ttermpro.exe の起動時のカレントフォルダは exe のパスになっているので
結果 ttermpro.exe からの相対パスになっているようです。

他のパスは後日チェックします。

**Comment by nmaya** [comment]
> r10980 で TERATERM.INI の UILanguageFile で絶対パス指定できるようにしました。

ありがとうございます。

> 他のパス

ソースを追いかけてみました。

trunk (r10980)

| key                             | 相対パスのフルパス化 | 相対パスの基準         |    |
| ------------------------------- | -------------------- | ---------------------- | -- |
| UILanguageFile                  | する                 | ts->ExeDirW            |    |
| ConfirmChangePasteStringFile    | しない               | カレントディレクトリ？ | 相対パスを fopen_s() に渡している |
| KnownHostsFiles                 | する                 | ts->HomeDirW と同一    |    |
| DefaultRhostsHostPrivateKeyFile | する                 | GetModuleFileName()    | 一度認証ダイアログを経由する |
| DefaultRSAPrivateKeyFile        | する                 | GetModuleFileName()    | 一度認証ダイアログを経由する |
| BGSPIPath                       | する                 | ts->HomeDirW           |    |
| BGThemeFile                     | する                 | ts->HomeDirW           |    |

4-stable (r10980)

| key                             | 相対パスのフルパス化 | 相対パスの基準         |    |
| ------------------------------- | -------------------- | ---------------------- | -- |
| UILanguageFile                  | する                 | ts->HomeDir            |    |
| ConfirmChangePasteStringFile    | しない               | カレントディレクトリ？ | 相対パスを fopen() に渡している |
| KnownHostsFiles                 | する                 | GetModuleFileName()    |    |
| DefaultRhostsHostPrivateKeyFile | する                 | GetModuleFileName()    |  一度認証ダイアログを経由する |
| DefaultRSAPrivateKeyFile        | する                 | GetModuleFileName()    |  一度認証ダイアログを経由する |
| BGSPIPath                       | する                 | カレントディレクトリ   | GetFullPathName() を使用 |
| BGThemeFile                     | する                 | ts->HomeDir            |    |

**Comment by zmatsuo** [comment]
> Tera Term 4 の相対パス指定のとき、
> カレントフォルダからの相対パスになっています。
> ttermpro.exe の起動時のカレントフォルダは exe のパスになっているので
> 結果 ttermpro.exe からの相対パスになっているようです。

間違っていました。
カレントディレクトリを exe のあるフォルダに設定して、
_fullpath() を使ってフルパスに変換しています。
そのあと元のカレントフォルダに戻していました。

**Comment by zmatsuo** [comment]
> ソースを追いかけてみました。

ありがとうございます。

r10983 で ConfirmChangePasteStringFile のファイル名が
相対パスの時、ts->HomeDir をベースとするようにしました。

これでカレントディレクトリを基準になっている設定ファイルはなくなったはずです。
