### ISSUE TITLE
LogTimestamp 設定がログダイアログに反映されない

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/osdn-download#24]
概要
設定でタイムスタンプを ON にしてもログダイアログでは外れてしまいます。

再現方法１
1) Explorer から ttermpro.exe をダブルクリックして起動する。
2) New Connection ダイアログを cancel する。
3) Setup -> Additional Settings... の Log タブで Timestamp にチェックを入れて OK する。
4) File -> Log でログダイアログを出す。Timestamp にチェックが入っていない。

再現方法２
1) 以下の２行だけの ini ファイルを用意する。
```
[Tera Term]
LogTimestamp=on
```
2) Explorer から ttermpro.exe をダブルクリックして起動する。
3) New Connection ダイアログを cancel する。
4) Setup -> Restore setup... を開き、上記で作成した iniファイルをリストアする。
5) File -> Log でログダイアログを出す。Timestamp にチェックが入っていない。

バージョン（ビルド）による切り分けは以下の通りです。
* 4.107          Timestamp にチェックが入っています。期待通りです。
* 5.0 r10790     Timestamp にチェックが入っています。期待通りです。
* 5.0 rc2 ～ 5.0 Timestamp にチェックが入りません。

環境
Windows10 22H2

**Comment by sempreff** [comment]
[r10798](https://osdn.net/projects/ttssh2/scm/svn/commits/10798) で落とされた ArrangeControls を戻してあげると期待の動作になるようです。
[patch.logdlg.txt](https://github.com/TeraTermProject/osdn-download/files/12919217/patch.logdlg.txt)

**Comment by zmatsuo** [comment]
ありがとうございます。

手もとで再現しました。
調べます。

**Comment by zmatsuo** [comment]
r11013で修正しました。

次のURLからバイナリをダウンロードできます。
https://ci.appveyor.com/project/teraterm/trunk-vs2022/build/artifacts

**Comment by sempreff** [comment]
ご対応ありがとうございます。snapshot で Timestamp については動作良好のようです。ありがとうございます。
Append の指定方法について違和感があります。

再現方法
0) デフォルトのファイル名で空ログファイルがある状態にします。
  （C:\Users\ユーザ名\AppData\Local\teraterm5\teraterm.log をメモ帳で作っておく、など）
1) Explorer から ttermpro.exe をダブルクリックして起動し、New Connection をキャンセルします。
2) Setup -> Additional Settings -> Log で Append のチェックを ON にして OK します。(Append はデフォルトで ON です）
3) File -> Log で Logダイアログを開くと、Write mode が New / Overwrite になっています。

**Comment by sempreff** [comment]
設定値と or する案はいかがでしょうか。
[patch2.logdlg.txt](https://github.com/TeraTermProject/osdn-download/files/13044822/patch2.logdlg.txt)

**Comment by nmaya** [comment]
確かに Append と Binary の設定値(ts)がログダイアログに反映されないようで、ご指摘はごもっともと思います。

Tera Term 5 では、「ログファイル名のエディットボックスに入っているファイル名が実在するかどうか」のチェックが常に走ります。

- 設定値(ts)が「Append=1」
- ご提案のパッチの「OR した値を使う」処理にする
- 実在するファイル名を指定する
- UIの値を「Append=0」=「New/Overwrite」に変更する

と、無理矢理 Append に戻されてしまう=「New/Overwrite を選択できない」という動作になります。

**Comment by sempreff** [comment]
ご確認ありがとうございます。考慮が足りておりませんでした。
やはり r10798 で落とされたダイアログ初期化時点の処理を戻してあげるのが良さそうに思います。
添付のような趣旨でいかがでしょうか。
[patch3.logdlg.txt](https://github.com/TeraTermProject/osdn-download/files/13053445/patch3.logdlg.txt)

**Comment by zmatsuo** [comment]
ダイアログが開くときに設定値を反映するようにしました。

ファイルが存在しないとき、
新規(上書き)/追記 ラジオボタンを
デフォルトに設定するようにしてみました。

試してみてください。
https://ci.appveyor.com/project/teraterm/trunk-vs2022/build/job/imyqcracl1h26evd/artifacts

ヘルプにも少し手を入れてみました。

**Comment by sempreff** [comment]
ご対応ならびにスナップショットありがとうございます、動作良好です。
- 設定画面で設定できるオプションがログダイアログに期待通り反映されることを確認できました。
- Explorer からダブルクリック起動 → New Connection キャンセル → Setup - Additional Settings - Log で Binary を ON → OK → File - Log した時に Plain Text と Timestamp が disable になるのに１秒ほどかかるのが少し気になりますが、（自分は）Binary でログを取ることはほぼないので、実用上、問題ではありません。
- この issue はクローズで大丈夫です。試しにクローズしてみます。

**Comment by zmatsuo** [comment]
> ファイルが存在しないとき、
> 新規(上書き)/追記 ラジオボタンを

ファイルが存在するとき、の誤りでした。
失礼しました。

> １秒ほどかかるのが少し気になりますが

それは気になります。

手もとでは遅れてdisableになる現象は出ていません。
Windowsのバージョンによって動作が違うことはあるかなと思います。

予想で修正してみました。
https://ci.appveyor.com/project/teraterm/trunk-vs2022/builds/48330124/artifacts
たびたびすみません、
試していただけますでしょうか。

**Comment by sempreff** [comment]
ダイアログが開いた時点で disable になる（＝期待の動作である）ことが確認できました。
（初期化時に  ArrangeControls することになったので、enable・disable は ArrangeControls に任せてよいのだと思います。つまり 300行目の EnableWindow は省略できそうです。ですが動作に問題ないので現状で問題ないと思います。）

**Comment by zmatsuo** [comment]
試していただきありがとうございます。

> ダイアログが開いた時点で disable になる（＝期待の動作である）ことが確認できました。

良かったです。

> EnableWindow は省略できそうです

r11019で削除しました。

ビルドしました。
https://ci.appveyor.com/project/teraterm/trunk-vs2022/builds/48334371/artifacts

**Comment by sempreff** [comment]
スナップショットありがとうございます。
動作良好です。
