### ISSUE TITLE
document typo: migrate_to_5.html

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/osdn-download#25]
概要
migrate_to_5.html (en,ja 両方) とも 一部の Tera Term が Tera Trem になっています。

[migrate_to_5_fixtypo.patch.txt](https://github.com/TeraTermProject/osdn-download/files/12919746/migrate_to_5_fixtypo.patch.txt)

**Comment by nmaya** [comment]
r11011 で修正しました。
