### ISSUE TITLE
chocolatey パッケージの更新

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/osdn-download#26]
TeraTermProject/chocolatey-package を更新する手順はこれであっていますか？

- ブランチを作成する
- 変更する
  - 変更履歴を更新（今回分のみ記載している）
    - teraterm/ReleaseNotes.md
    - teraterm/teraterm.nuspec
  - バージョンを更新
    - teraterm/teraterm.nuspec
  - Copyright年を更新（あれば）
    - teraterm/teraterm.nuspec
  - ダウンロードURL・チェックサムを更新
    - teraterm/tools/chocolateyinstall.ps1
- マージする
  - 今までの履歴を見ると GitHub Web UI の "Rebase and merge"？
- タグを作る

ここまで作業したあと、chocolatey への更新はどのように行いますか？

**Comment by ttdoda** [comment]
とりあえず更新用のメモを貼っておきます。
```
1. branchの作成
  git checkout -b teraterm-4.xx

2. ReleaseNotes.md の更新

3. commit
  git add ReleaseNotes.md
  git commit

4. origin に push
  git push origin teraterm-4.xx

5. ReleaseNotes.md の確認
  https://github.com/ttdoda/chocolatey-package/blob/teraterm-4.xx/teraterm/ReleaseNotes.md

6. teraterm.nuspec の更新
  変更点:
    バージョン番号更新
    <version>4.xx</version>

    Copyright の年を更新 (年が変わった時のみ)
    <copyright>...</copyright>

    ReleaseNotes の更新 (ReleaseNotes.md を読み込む)
    <releaseNotes>
    ...
    </releaseNotes>

7. tools/chocolateyinstall.ps1 の更新
  変更点:
    インストーラのURL更新 (バージョン番号の変更だけでOK)
    $url   = 'https://osdn.net/dl/ttssh2/teraterm-4.xx.exe'

    checksumの更新
    ダウンロードページに行き、インストーラの sha256 checksum をコピペ
    checksum   = 'xxxxxxxxxxxxxxxxxxxxxxxxxx'

8. パッケージの作成
  choco pack

9. テスト
  sudo choco upgrade teraterm -s . --version 4.xx -y

  C:\ProgramData\Chocolatey\logs\choco.summary.log を確認する。

  Tera Term の起動確認

  sudo choco uninstall teraterm -y
  sudo choco install teraterm -s . -y

  C:\ProgramData\Chocolatey\logs\choco.summary.log を確認する。

  Tera Term の起動確認

10 作成したパッケージを chocolatey へ push
  choco push teraterm.4.xx.nupkg

11 commit & push
  git add teraterm.nuspec tools/chocolateyinstall.ps1
  git commit
  git tag v4.xx
  git push origin teraterm-4.xx
  git push TeraTermProject teraterm-4.xx

  git checkout teraterm
  git merge teraterm-4.xx
  git push TeraTermProject master

  git checkout master
  git merge teraterm-4.xx
  git push

  git push origin --tags
  git push TeraTermProject --tags
```

**Comment by ttdoda** [comment]
>   * 変更履歴を更新（今回分のみ記載している）
>     
>     * teraterm/ReleaseNotes.md
>     * teraterm/teraterm.nuspec

実際に必要なのは`teraterm.nuspec`の方だけです。
ReleaseNotes.mdは、独立してファイルが有った方が書きやすい&pushして表示を確認しやすいという事で作った作業用のファイルです。
teraterm.nuspecを直接書き換えるのならばReleaseNotes.mdを変更する必要はありません。

>     * teraterm/tools/chocolateyinstall.ps1
> * マージする
>   
>   * 今までの履歴を見ると GitHub Web UI の "Rebase and merge"？

現状ではGitHubのWeb UIを使わずに直接pushしています。


> ここまで作業したあと、chocolatey への更新はどのように行いますか？

`choco push` で行いますが、事前に`choco apikey`でAPIキーを設定しておく必要があります。(1度行えば以降は必要無し)
APIキーは https://community.chocolatey.org で Sign in して、Account の API Key で確認できます。
Chocolateyへのログイン情報はOSDNのWikiに書いておいたはずです。

**Comment by ttdoda** [comment]
とりあえず最低限の変更を入れて、4.107をpushしておきました。
https://community.chocolatey.org/packages/teraterm/4.107

現状、4.106がOSDNの不調でインストールできないので最低限の変更だけで更新しましたが、
teraterm.nuspecに書かれているいくつかのOSDNのURLを変えてから再度更新する方がいいと思います。

  * projectUrl: https://ttssh2.osdn.jp/
  * licenseUrl: https://ttssh2.osdn.jp/manual/en/about/copyright.html
  * projectSourceUrl: https://osdn.net/projects/ttssh2/scm/svn/
  * docsUrl: https://ttssh2.osdn.jp/manual/en/
  * bugTrackerUrl: https://osdn.net/projects/ttssh2/ticket/

**Comment by ttdoda** [comment]
projectSourceUrlとbugTrackerUrlが正常にアクセス出来なくてValidation Testing Failedとなってしまいました。
projectSourceUrlはとりあえずは https://github.com/TeraTermProject/teraterm-mirror-gitsvn でしょうか?
bugTrackerUrlは https://github.com/TeraTermProject/osdn-download/issues でいいですよね。

**Comment by zmatsuo** [comment]
> projectSourceUrlとbugTrackerUrlが正常にアクセス出来なくて

今リポジトリを引っ越してはどうかとttssh2-devにメールしたところでした。
移動してから更新するのはどうでしょうか

ミラーが作れているので特に問題なく引っ越しできるだろうと予想しています。

**Comment by nmaya** [comment]
> とりあえず更新用のメモ

> とりあえず最低限の変更を入れて、4.107をpushしておきました。 

対応ありがとうございます。

> 移動してから更新するのはどうでしょうか

同じバージョンで後から差し替えられるなら、今あるURLでやってしまっていいと思います。

**Comment by nmaya** [comment]
URLを差し替えてコミットしました。 https://github.com/TeraTermProject/chocolatey-package/commit/0f1e688e15099a8a6752703698ad347939ec9d47

`choco pack` して作成されたファイルが `teraterm.4.107.0.nupkg` だったので `teraterm.4.107.nupkg` にリネームして `choco push` したのですが、chocolatey 上では [4.107.0](https://community.chocolatey.org/packages/teraterm/4.107.0) として登録されてしまいました。
- `choco pack --version 4.107` としても、作成されるのは `teraterm.4.107.0.nupkg` で、nupkg の中の nuspec の version は 4.107.0 になってしまいます。`4.107` としてパッケージを作るにはどうしたらいいでしょうか？
- chocolatey に上がった 4.107.0 を削除する方法はあるでしょうか？

**Comment by nmaya** [comment]
> [4.107.0](https://community.chocolatey.org/packages/teraterm/4.107.0) として登録されてしまいました。

chocolatey に[聞いてみた](https://github.com/chocolatey/choco/issues/3356#issuecomment-1793605928)ところ、[chocolatey 2.0 からはバージョン番号が正規化されて、強制的に x.y.z 形式にされる](https://docs.chocolatey.org/en-us/choco/features/version-number-normalization)とのことでした。

今後ですが、どちらがよいと思いますか？
- chocolatey パッケージを作るときは必ず chocolatey 1.4 を使用する（2.x を使わない）
  - 今から新規に 1.4 環境を構築できないといけない
- chocolatey 2.x を使い、chocolatey では x.y.z 形式にする（4.107.0, 5.0.0）

私が push した 4.107.0 は現在 moderation になっています。このあとこれがどうなるかわかりません。
もしも「プロジェクトサイト」（https://ttssh2.osdn.net ）も変更するなら、再度 nuspec を変更して push する可能性がありますので、どうするか考えておくべきです。

**Comment by nmaya** [comment]
プロジェクトWebサイトが変わったので差し替えられないか試してみました。
Chocolatey 1.4.0 環境を作成して teraterm.nuspec を書き換えて push してみましたが、同じバージョン番号で上書きはできないようでした。

```
> choco push teraterm.4.107.0.nupkg
Chocolatey v1.4.0
Attempting to push teraterm.4.107.0.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository or a nuspec element is invalid. See error below...
Failed to process request. 'Conflict'.
The remote server returned an error: (409) Conflict..
```

chocolatey のみ 4.107.1 というバージョンを振ればできそうですが、中身とバージョン番号がずれるので気が進みません。

**Comment by nmaya** [comment]
4.108 が上がっていることを確認しました。
https://community.chocolatey.org/packages/teraterm/4.108
