### ISSUE TITLE
Tera Term 5 の chocolatey への登録

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/osdn-download#27]
chocolatey の現在のパッケージ "teraterm" を 5.0 にアップデートしますか？
それとも "teraterm5" のような新しいパッケージを作成した方がよいと思いますか？

**Comment by ttdoda** [comment]
両方をインストール出来るようになっているので、新しく teraterm5 を作る方が良いように思います。

**Comment by ttdoda** [comment]
考えが変わって、以下の理由から既存のパッケージを5.0にアップデートする方がいいように思えてきました。

  * バージョン違いを別パッケージにしているソフトが少ない (見つからなかった)
  * 既存のユーザーの5.0への移行を促したい

先に手で5.0を入れていた場合にアンインストールがうまく行かなくなるのと、デフォルトのインストール場所が変わる事への対処が課題ですが。

**Comment by nmaya** [comment]
たしかにしれっと差し替えられたらいいですが、まだ5へアップデートしたくない人が上げられてしまった場合、4がアンインストールされずに残っていた方がいいでしょうか？

そういう人は4.107になってほしいところだと思いますが、4.107と5.0のパッケージを上げておけばchocolateyでバージョンを指定してバージョンダウンが可能でしょうか？

> 先に手で5.0を入れていた場合にアンインストールがうまく行かなくなる

それは4の手動インストールとchocolateyでの管理でも起こる問題でしょうか？

**Comment by nmaya** [comment]
winget は別扱いにしたみたいですね。

https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TeraTermProject

```
Tera Term   TeraTermProject.teraterm  4.107                    winget
Tera Term 5 TeraTermProject.teraterm5 5.0        Tag: teraterm winget
```

**Comment by nmaya** [comment]
[teraterm5](https://community.chocolatey.org/packages/teraterm5) での登録を確認しました。

https://community.chocolatey.org/packages/teraterm5/5.1 の push ありがとうございます。
