### ISSUE TITLE
F1キーでヘルプを開こうとする

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#28]
VTウィンドウでF1キーを押した時、ヘルプファイルを開こうとして、
`HTMLヘルプ(C:\Program Files (x86)\teraterm5\teratermj.chm)を開けません.`
というエラーダイアログが表示される。

この時、F1キーに設定されたキーのシーケンスは送出されない。

## バージョン
Tera Term 5.0で発生。おそらくr10807から。

**Comment by zmatsuo** [comment]
r10807が原因のようです。
調べます。

**Comment by zmatsuo** [comment]
r11012で修正しました。

次のURLにバイナリがあります。
https://ci.appveyor.com/project/teraterm/trunk-vs2022/build/artifacts

**Comment by zmatsuo** [comment]
クローズします。
問題がありましたら、再度オープンしてください。
