### ISSUE TITLE
TeraTearm5.0のSCPでファイル転送が出来ない

### ISSUE THREAD

**Issue by Phantom1104** [TeraTermProject/osdn-download#29]
[ファイル]→[SSH SCP...]にてファイルを転送しようとしましたが、以下のメッセージが出て転送に失敗します。

```
TTSSH: ファイルオープンエラー

読み取り用にファイルを開けません。この操作を正しく終了しました。
```

TeraTerm 4.106では同様の操作で問題なく転送が可能です。4.107は未確認。

**Comment by zmatsuo** [comment]
ありがとうございます。

ファイルの送信で、
送信元ファイルに漢字(アルファベット数字等以外)などが入った
フォルダ/ファイル名のファイルを指定したときに
発生したのではないかと思います。

手もとで再現しました。
調査します。

**Comment by zmatsuo** [comment]
ダイアログ、ファイル名の扱いなどUnicodeに対応していなかったので修正しました。

https://ci.appveyor.com/project/teraterm/trunk-vs2022/builds/48336226/artifacts

**Comment by zmatsuo** [comment]
クローズします。
問題がありましたら、再度オープンしてください。
