### ISSUE TITLE
タイトルスタックが正しく働かない

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#3]
Vim 8.2以降では`set title`を行った時にタイトルスタックを利用してVim終了時に起動前のウィンドウタイトルに戻るが、これが正しく働かずにVim終了時にウィンドウタイトルが "Thanks for flying Vim" となる。

## 再現手順
「設定」-「その他の設定」-「制御シーケンス」にある「ウィンドウタイトルの変更要求を受け入れる」を`上書き`に設定する。
Vim 8.2以降を起動する。
`:set title` を実行すると、ウィンドウタイトルが`[無名] - VIM`に変わる。
`:q`を実行してVimを終了する。

### 期待した動作
ウィンドウタイトルがVim起動前の状態に戻る。

### 実際の動作
ウィンドウタイトルが`Thanks for flying Vim`になる。
ただし、Vim起動前に`echo -e "\e]0;title\a"`を実行してウィンドウタイトルを変更してあるとその状態に戻る。
この状態で「コントロール」-「リモートタイトルリセット」を実行した後、再現手順を実行すると現象が再現する。
ウィンドウタイトルが未設定の時にタイトルスタックへの保存が正しく動かない?

## 再現手順2
制御シーケンスレベルでの再現手順。
前提条件
 * 「設定」-「その他の設定」-「制御シーケンス」にある「ウィンドウタイトルの変更要求を受け入れる」が`上書き`に設定されている
 * サーバーログイン直後(タイトル設定が行われていない状態)、または「コントロール」-「リモートタイトルリセット」を実行した後
 * bash等では設定によってはタイトル変更が行われるので、その機能を使わないように設定する。もしくはzsh等の他のシェルを使う

```
# 現在のタイトルをタイトルスタックに保存する
echo -e "\e[22;0t"

# ウィンドウタイトルを changed に変更する
echo -e "\e]0;changed\a"

# タイトルスタックからタイトルを復元する
echo -e "\e[23;0t"
# => ウィンドウタイトルが初期状態になるのが正しい動作だが、changed のままとなる

# ウィンドウタイトルを new title に変更する
echo -e "\e]0;new title\a"

# 現在のタイトルをタイトルスタックに保存する
echo -e "\e[22;0t"

# ウィンドウタイトルを changed に変更する
echo -e "\e]0;changed\a"

# タイトルスタックからタイトルを復元する
echo -e "\e[23;0t"
# => ウィンドウタイトルが new title に戻る
```

## バージョン
5.0 RC で再現。
5.0 Beta, 4.107 RC2では問題なし。

**Comment by zmatsuo** [comment]
r10936で修正しました。

**Comment by nmaya** [comment]
修正されたことを確認しました。
