### ISSUE TITLE
リポジトリを引っ越したあとで調査する案件

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/osdn-download#30]
- https://osdn.net/projects/ttssh2/ticket/48873
  - settitle に日本語を渡すと落ちる
- TTXCommandLineOpt の /FG=, /BG= が効かない
  - プラグインは VTColor[0], VTColor[1] を書き替えている
- TeraTerm Menu の設定名に5Cを含む文字が使えない
- https://osdn.net/projects/ttssh2/ticket/48870
  - 460800baudということはシリアル
  - SSH接続・数十バイトのファイル2個/数百KBのファイル2個 では再現せず

**Comment by zmatsuo** [comment]
SetTitle に日本語を渡すと落ちる 件、原因と対策がわかりました。
GetTitle は落ちませんが日本語は文字化けします。
LoadKeyMap も日本語を含んだファイル名だと読み込みに失敗するはずです。
リポジトリを引っ越した後修正を入れようと思います。

**Comment by nmaya** [comment]
teraterm リポジトリの issue へ移動
