### ISSUE TITLE
公開鍵認証で接続したSSHセッションを複製できないことがある

### ISSUE THREAD

**Issue by wakatono** [TeraTermProject/osdn-download#31]
日本語を含む名前のフォルダにある秘密鍵を指定すると、[ファイル]→[セッション複製] が失敗します。
秘密鍵ファイルの名前に、例えば"id_あーるえすえー"みたいに日本語が含まれている場合も、同じようにセッション複製が失敗します。
見た感じ、TeraTermでの秘密鍵ファイルを示すパス名内の日本語文字列（に限らず、マルチバイト文字列）の扱いに誤りがあるように思います。
なお、新規接続時にそのようなファイルを指定した場合は、問題なく接続を行えます。

**Comment by zmatsuo** [comment]
ありがとうございます。

ttxssh.c の TTXSetCommandLine() 内、
 _snwprintf_s(tmp, _countof(tmp), _TRUNCATE, L" /keyfile=%hs", mark);
で文字化けしていました。

Unicodeに変換する時、特に設定していないと、
Cのランタイムは元の文字列が日本語(CP932)文字列として
扱ってくれないんですね。

r11023 で setlocale() を使って設定するようにしました。

https://ci.appveyor.com/project/teraterm/trunk-vs2022/builds/48383143/artifacts

**Comment by zmatsuo** [comment]
ありがとうございました。
クローズします。
