### ISSUE TITLE
tag 書式として v0.0 を検討してほしい

### ISSUE THREAD

**Issue by topstone** [TeraTermProject/osdn-download#32]
[Scoop](https://scoop.sh/) で [Tera Term を扱おうとしています](https://github.com/ScoopInstaller/Extras/pull/12099)が、Tera Term の tag 書式が[一般的な書式 (v0.0 式)](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases) でないためうまくいかない状況です。 

開発上の差支えがなければ、一般的な書式を検討していただけないでしょうか。

**Comment by nmaya** [comment]
正式なリポジトリは[ここ](https://github.com/TeraTermProject/osdn-download) ではなく https://github.com/TeraTermProject/teraterm になりました。

v0.0 形式の tag を使ってリリースを作成しました。

**Comment by topstone** [comment]
ありがとうございます。
