### ISSUE TITLE
TeraTerm 5.0: TTL Script fails at 'sendfile'

### ISSUE THREAD

**Issue by Nippey** [TeraTermProject/osdn-download#33]
Hello,

I just discovered an issue while updating from 4.107 to 5.0:

I have a script that executes:

```
FLASHWRITER_FILE = 'xxxxxxx.mot'
getdir DIR

sprintf2 FILE_NAME '%s\%s' DIR FLASHWRITER_FILE
sendfile FILE_NAME 1
```

I can see that the file is already sent to the device, but still, macro execution is stuck at line 'sendfile FILE_NAME 1'.

Can I provide any additional information to you?
Best Regards!

**Comment by nmaya** [comment]
Hi,

Thank you for your report, and I confirmed that this issue is reproduced.

By the way, this repository `TeraTermProject/osdn-download` is planned to archive.
Could you please post same report to [TeraTermProject/teraterm](https://github.com/TeraTermProject/teraterm) as a new issue?

Thank you.

**Comment by Nippey** [comment]
Thank you for your reply!
I will report to */teraterm
