### ISSUE TITLE
Teraterm5.0のデフォルトのインストール先を、今まで通り「teraterm」にしてほしい

### ISSUE THREAD

**Issue by kitudon** [TeraTermProject/osdn-download#34]
Teraterm5.0のデフォルトのインストール先フォルダが「teraterm5」になりましたが、できましたら今まで通り「teraterm」にしていただきたいです。

自動でteratermを起動する仕組みがあるのですが、その起動パスを変更する必要性が発生しました。
また、複数の人が使用する中で、4系環境と5系環境が混在しているとその辺りも考慮する必要があります。
そのため、勝手ながらこのような要望を出させていただきました。
ご検討いただけますと大変助かります。

**Comment by nmaya** [comment]
リクエストありがとうございます。

「Tera Term 5 は 4 と内部動作が違うので様子を見たい」「なにか 5 特有の問題があったときに 4 を使える状態にしておきたい」という理由で、同じPCに同居させたいユーザも多いと思います。
「ひとつの PC にすでに Tera Term (4) が入っていて、新たに Tera Term 5 をインストールする」という状況では、デフォルトのインストール先が同じだと既存の Tera Term (4) が上書きされてしまい、取り返しが付かなくなります。

それに比べて、インストール先をデフォルトの「teraterm5」から「teraterm」へ変更することは容易です。新規インストールであれば破壊は起こりませんし、意図して変えたのなら上書きされても自己責任です。
また、どのように起動しているかわかりませんが、実行ファイルの実在を確認して起動したり、どちらインストール先もPATHに含めてフルパスではない起動をするなどの対応ができそうです。

このように影響の大きさを比較衡量し、このリクエストはお受けできません。

**Comment by kitudon** [comment]
早速のご回答ありがとうございます。
また、「teraterm5」とした意図についても詳しくご説明ありがとうございます。理解いたしました。
おっしゃる通り起動パスの対応で考えていこうと思います。
いつも便利に使わせていただいております。これからもよろしくお願いいたします。

**Comment by nmaya** [comment]
ご理解ありがとうございます。
