### ISSUE TITLE
Non-Standard build version

### ISSUE THREAD

**Issue by LeeViewB** [TeraTermProject/osdn-download#35]
This is the build currently being written as a DisplayVersion:
![image](https://github.com/TeraTermProject/osdn-download/assets/31350302/35ceeb36-588f-498c-a472-3a52325d23d8)

This is a non-standard build version and it generates issues when this software is deployed as a WSUS update.

Would it be possible to use build version numbers following [best practices](https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee535064(v=office.14)) with future releases?

**Comment by nmaya** [comment]
Hi,

It is already resolved in Tera Term 5.1.

Thanks,
