### ISSUE TITLE
OSDNからの離脱

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/osdn-download#6]
# OSDNの状況

### 2023/11/17時点

| 機能 | 状況 |
| ---- | ---- |
| プロジェクトページ以下 | 502, 504, とても重い |
| プロジェクトWebページ | レスポンスなし |

（2023/11/16から）

### 2023/09/17時点の状況

| 機能 | 状況 |
| ---- | ---- |
| プロジェクトページ | 重い |
| プロジェクトWebページ | 正常 |
| ダウンロードページ | 重い |
| ソースコードリポジトリ | 正常 |
| リポジトリブラウザ | 重い |
| メーリングリスト | 正常 |
| メーリングリストアーカイブ | 重い |
| ticket | 重い |
| wiki | 重い |
| ストレージ | 重い |

### これまでの状況
![downtime](https://github.com/TeraTermProject/osdn-download/assets/5668936/5a17898f-2fdf-4090-8f4f-e29859b94485)

### その他
- 障害への対応がない
  - ticket への反応もない
- サービス障害についてのアナウンスがない
- サービスが不安定で使いづらいというユーザの意見がある

## 別会社へ移管された[^4][^5]
- サービスが移管されたことのアナウンスがサイトにない
- 移管先が不安で利用したくないというユーザの意見がある

## TeraTerm Project としての判断
- 「少なくともサービス障害を起こしている機能に関しては OSDN の利用を中止する」でよいか？

# 移行先をどうするか

## 候補
- GitHub
- sourceforge.net
  - 過去に、インストーラにアドウェアを仕込むという事件[^1][^2][^3]があった

## TeraTerm Project としての判断
- 移行先は GitHubでよいか？

[^1]: https://shujisado.com/2021/11/09/goodbyosdn/#12
[^2]: https://it.srad.jp/story/15/05/28/087214/
[^3]: https://opensource.srad.jp/story/15/06/02/0924222/
[^4]: https://forest.watch.impress.co.jp/docs/news/1520393.html
[^5]: https://opensource.srad.jp/story/23/07/27/0555240/

**Comment by nmaya** [comment]
移行案1
| 機能 | サービス |
| ---- | -------- |
| プロジェクトページ | GitHub(https://github.com/TeraTermProject/) |
| プロジェクトWebサイト | 要検討 #7 |
| ダウンロードページ | GitHub(https://github.com/TeraTermProject/ttssh2/releases) |
| ソースコードリポジトリ | GitHub(https://github.com/TeraTermProject/ttssh2.git) |
| リポジトリブラウザ | GitHub(https://github.com/TeraTermProject/ttssh2) |
| メーリングリスト | OSDN(ttssh2-dev, ttssh2-users) |
| メーリングリストアーカイブ | 要検討 |
| ticket | GitHub(https://github.com/TeraTermProject/ttssh2/issues) |
| wiki | GitHub(https://github.com/TeraTermProject/ttssh2/wiki) |
| ストレージ | wikiへの添付で代用 |

※ GitHub リポジトリ名の ttssh2 は仮

**Comment by zmatsuo** [comment]
> 「少なくともサービス障害を起こしている機能に関しては OSDN の利用を中止する」でよいか？

よいと思います。

最近はチケットを見るだけに苦労する(書き込むのは不可能に近い)のはとても困ります。

移行作戦案はないのですが、
一気に引っ越しは大変なので、障害を起こしている機能からでしょうか。

> 移行先は GitHubでよいか？

他の移行先を評価したわけではないのですが
ここGitHubでいいのではないでしょうか。

一部を他のサービス(例えばプロジェクトのwebページだけとか)と
合わせて使うのもよさそうですよね。

他のサービスが素晴らしことがわかったらそのときまた検討しましょうか。
(再度引っ越しは大変ですが)

**Comment by nmaya** [comment]
> > 「少なくともサービス障害を起こしている機能に関しては OSDN の利用を中止する」でよいか？
> 
> よいと思います。
> 
> 最近はチケットを見るだけに苦労する(書き込むのは不可能に近い)のはとても困ります。
> 
> > 移行先は GitHubでよいか？
> 
> 他の移行先を評価したわけではないのですが ここGitHubでいいのではないでしょうか。
> 
> 一部を他のサービス(例えばプロジェクトのwebページだけとか)と 合わせて使うのもよさそうですよね。

ご意見ありがとうございます。
取り得る選択肢、現実的であろうと私が思う案、そのためのTODOを #4 やその子供たちや [移行案1](https://github.com/TeraTermProject/osdn-download/issues/6#issuecomment-1722382823) に書いています。依存関係のあるものもありますが、サービスごとに決めていければと思います。

> 移行作戦案はないのですが、 一気に引っ越しは大変なので、障害を起こしている機能からでしょうか。

- #4 の「確認が必要な点」はプロジェクトの決定が必要な件
- 決まると[移行案](https://github.com/TeraTermProject/osdn-download/issues/6#issuecomment-1722382823)の完成版ができる
- そうすると #4 の「タスク管理」の項目が決まる
- #4 の「タスク管理」を順番に行う

というイメージでいます。

**Comment by topias11a705** [comment]
release note(改訂履歴)はGithubのWikiに記載されるようになる認識で合ってますでしょうか？
https://ttssh2.osdn.jp/manual/4/ja/about/history.html

**Comment by nmaya** [comment]
- `*.osdn.net` のSSL証明書が 2023-10-16 で切れた
  - SVNへHTTPSでアクセスができない
  - static-cdn.osdn.netへHTTPSでアクセスができない
    - osdn.net内のcssやjsが読み込まれない
- `dl.osdn.net` のSSL証明書が 2023-10-15 で切れた
  - https://osdn.net/projects/support/ticket/48859

**Comment by nmaya** [comment]
> > 「少なくともサービス障害を起こしている機能に関しては OSDN の利用を中止する」でよいか？
> 
> よいと思います。

これをもって決定されたものとし、close します。
