### ISSUE TITLE
Rekeyが正しく行われない

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#8]
通信量が大きくなってサーバー側からRekeyが行われた時に正常に終了せず、応答が無くなったり、「現在のステージでは想定外のSSH2 メッセージ(xx) です.」というダイアログが表示されて通信が終了する。

## バージョン
4.107 RC2, 5.0 RCで再現。
4.106では問題なし。

**Comment by nmaya** [comment]
これはリリースに含めるべきと考えます。

**Comment by nmaya** [comment]
cf. https://osdn.net/projects/ttssh2/ticket/36109#comment:1412:36109:1684838812

**Comment by nmaya** [comment]
再現させる方法や、使っていてどの程度の頻度で起こるのかといった情報をもとに、リリースを遅らせてでも対応を入れるか考えたいと思います。

**Comment by zmatsuo** [comment]
サーバー側の
/etc/ssh/sshd_config
に
RekeyLimit default 1
を追加しました。
使用バージョンは
/usr/sbin/sshd -V
OpenSSH_9.2, OpenSSL 3.0.9 30 May 2023
です。

この状態で tera term 5.0 rc で
パスワード認証で接続すると
送受信ができなくなって、使用できない状態を
すぐに再現できることがわかりました。

動作する/動作しない リビジョンを調べてみました。

```
rev.          date       ok/ng
r10612 beta1  2023/02/28 ng
r10238        2022/09/05 ng
r10062        2022/07/16 ok
r9848  alpha1 2022/04/04 ok
```

ok->ng の間で、連続して ttxssh の変更が入っています。
この中のどこかで発生する状態になったようです。

**Comment by nmaya** [comment]
### RekeyLimit
https://man.openbsd.org/sshd_config
データ量: between ‘1G’ and ‘4G’, depending on the cipher
秒数: none
がデフォルトなんですね。
SCPで送受信を繰り返していたら超えそうなデータ量です。
手元では落ちませんでしたが、disconnectにならないのに操作できなくなりました。発生したときに何が起きたか分かりづらく、ユーザにとってよくない現象です。

### どこから発生するか
[r10066](https://github.com/TeraTermProject/teraterm-mirror-gitsvn/commit/b556c81690a4e7a17277569b19823afcc86df582) みたいです。

**Comment by ttdoda** [comment]
Port ForwardingでRDPを通していると、一日に1～2回落ちます。
今までもRekey時に別の原因でRDPだけが落ちる事が有ったのですが、
今は確実にTera Termごと落ちるのでかなり良くない状況ですね。

r10073でKEX周りを大きくいじっているので、ここでエンバグしていると思います。

**Comment by nmaya** [comment]
# 過去の変更
[r10066](https://github.com/TeraTermProject/teraterm-mirror-gitsvn/commit/b556c81690a4e7a17277569b19823afcc86df582#diff-b213bba533e8c2c25ee480e7e909b988cbe08904269de42b78df67d98ffafa68R6645-R6652), [r10073](https://github.com/TeraTermProject/teraterm-mirror-gitsvn/commit/4022520921049effda5b969ba6aae22a870db6df)

# おかしそうなところ
ログを見ながらコードを追いかけてみると、Rekey のときには SSH_MSG_NEWKEYS を送信していない？
```
2023-09-20 12:54:11.077Z [4264] SSH2_MSG_KEXINIT was received.
(snip)
2023-09-20 12:54:11.337Z [4264] KEX algorithm: diffie-hellman-group14-sha1
2023-09-20 12:54:11.348Z [4264] server host key algorithm: ecdsa-sha2-nistp256
2023-09-20 12:54:11.358Z [4264] encryption algorithm client to server: aes256-cbc
2023-09-20 12:54:11.369Z [4264] encryption algorithm server to client: aes256-cbc
2023-09-20 12:54:11.380Z [4264] MAC algorithm client to server: hmac-sha2-256
2023-09-20 12:54:11.391Z [4264] MAC algorithm server to client: hmac-sha2-256
2023-09-20 12:54:11.402Z [4264] compression algorithm client to server: none
2023-09-20 12:54:11.414Z [4264] compression algorithm server to client: none
2023-09-20 12:54:11.702Z [4264] SSH2_MSG_KEXDH_INIT was sent at SSH2_dh_kex_init().
2023-09-20 12:54:11.713Z [4264] SSH2_MSG_KEXDH_REPLY was received.
2023-09-20 12:54:12.055Z [4264] SSH2_MSG_NEWKEYS was received(DH key generation is completed).
2023-09-20 12:54:12.069Z [4264] SSH2_send_channel_data: now rekeying. data is not sent.
```

## pvar->kex_status の遷移
### 初回接続時
- スタート / SSH_init()
```
pvar->kex_status = 0; // フラグ初期化
```
- SSH_MSG_NEWKEYS 送信 / ssh2_send_newkeys()
```
// SSH_MSG_NEWKEYS 送信
pvar->kex_status |= KEX_FLAG_NEWKEYS_SENT;
```
- SSH_MSG_NEWKEYS 受信 / handle_SSH2_newkeys()
```
pvar->kex_status |= KEX_FLAG_NEWKEYS_RECEIVED;
// KEX_FLAG_NEWKEYS_SENT && !KEX_FLAG_REKEYING の処理を通る
pvar->kex_status = KEX_FLAG_KEXDONE; // 今までのフラグは全クリア
```

### Rekey時（サーバから）
- SSH_MSG_KEXINIT 受信 / handle_SSH2_kexinit()
```
if (pvar->kex_status == KEX_FLAG_KEXDONE) {
    pvar->kex_status = KEX_FLAG_REKEYING; // フラグが全クリアされる
    SSH2_send_kexinit(pvar); // SSH_MSG_KEXINIT 送信
}
SSH2_xxx_kex_init() // KEX 開始
```
- SSH_MSG_NEWKEYS 受信 / handle_SSH2_newkeys()
```
pvar->kex_status |= KEX_FLAG_NEWKEYS_RECEIVED;
※KEX_FLAG_NEWKEYS_SENT が有効ではないので、何の処理もない
ここで SSH_MSG_NEWKEYS を送信すべき？それとももっと前で？
```

# その他 Rekey まわりで気になる点
- Rekey 中のパケット ... 保留にならず破棄されている（ソース中のコメントより）
- KexKeyLogFile を有効にして Wireshark で見ていると、Rekey 時の SSH_MSG_KEXINIT から暗号解除ができない
  - SSH_MSG_NEWKEYS が完了するまでは見えるはず（その結果欠けることはない）と思っていたが、そうではない？
- クライアントからのRekey ... 実装されていない

**Comment by nmaya** [comment]
@ttdoda r10943 の修正をコミットしましたが、これで問題ないでしょうか？

**Comment by zmatsuo** [comment]
動作確認しました。
- r10941 通信が止まる、
- r10943 止まらず使用し続けることができる

**Comment by nmaya** [comment]
> 動作確認しました。
> 
> * r10941 通信が止まる、
> * r10943 止まらず使用し続けることができる

確認ありがとうございます。

**Comment by nmaya** [comment]
4-stable にも同じ修正をすると、通信が止まる問題が出ないことを確認しました。

**Comment by zmatsuo** [comment]
> 一日に1～2回落ちます。

この状態が改善されていればいいのですが・・。

> 4-stable にも同じ修正をすると、通信が止まる問題が出ないことを確認しました。

RekeyLimit を変更したサーバーに接続して使えていれば
とりあえず大丈夫なのかなと思います。

この変更を入れたRC2を作ってみるのはどうでしょうか?

**Comment by nmaya** [comment]
https://github.com/TeraTermProject/osdn-download/releases/tag/teraterm-5.0_rc2
https://github.com/TeraTermProject/osdn-download/releases/tag/teraterm-4_107_rc3
バイナリを作成しました。
OSDNへはあとでアップします。

**Comment by ttdoda** [comment]
まだ落ちます。
多分 Ticket #36111 (https://osdn.net/projects/ttssh2/ticket/36111) の残件を踏んでます。

**Comment by nmaya** [comment]
修正を入れた turnk のバイナリです。これでも落ちるでしょうか？
https://ci.appveyor.com/project/teraterm/trunk-vs2022/builds/48155813/artifacts

**Comment by ttdoda** [comment]
問題無いと思います。

**Comment by ttdoda** [comment]
## メモ
OpenSSH 7.2～7.9ではRekey時のext-inf-cに反応してSSH_MSG_NEWKEYSの後にSSH_MSG_EXT_INFOを送ってくる。
これはRFC 8308でSSH_MSG_EXT_INFOを送っていいタイミングとされている `As the next packet following the server's first SSH_MSG_NEWKEYS.` に合わない為8.0で修正された。

このRekey時のSSH_MSG_EXT_INFOがttsshで想定しないタイミングで送られて来ている為、エラーとして終了していた。
ただし、そもそも ext-info-c を送るタイミングは`first key excahnge`とされているので修正は必要。

c.f.
https://bugzilla.mindrot.org/show_bug.cgi?id=2929
https://www.openssh.com/releasenotes.html#8.0
```
 * sshd(8): Only consider the ext-info-c extension during the initial
   key eschange. It shouldn't be sent in subsequent ones, but if it
   is present we should ignore it. This prevents sshd from sending a
   SSH_MSG_EXT_INFO for REKEX for buggy these clients; bz#2929
```

**Comment by ttdoda** [comment]
> * Rekey 中のパケット ... 保留にならず破棄されている（ソース中のコメントより）

https://github.com/TeraTermProject/osdn-download/issues/8#issuecomment-1722647644 で書いた別の原因で落ちるというのがおそらくこれが原因ですね。データが欠けてRDPサーバー側で復号出来なくなって切られていると思います。
あと、SCP送信でデータが欠けます。これはRekeyLimitを変える事によって簡単に再現できると思います。
普通の使い方だとあまり踏まないと思いますが、別Issueを立てて対応した方がいいかもしれません。

**Comment by nmaya** [comment]
> 修正は必要。

仕様と動作を把握しきっていないので質問します。
これは「修正が必要だったが、修正済みである（Unexpected SSH2 message on current stage ではなく、ハンドラが処理するようにした r10066）」ですか？
それとも「修正が必要で、修正されていない（ハンドラが処理するのはよいが、初回以外は無視するようになっていない）」ですか？

**Comment by ttdoda** [comment]
あいまいですみません。Rekeyでext-info-cを送るのが間違っているので修正が必要だったという事です。
r10949の修正が無くてもOpenSSH 8.0以降ならば動いたが、RFC的にはr10949の修正は必須だったという事です。

**Comment by nmaya** [comment]
> r10949の修正が無くてもOpenSSH 8.0以降ならば動いたが、RFC的にはr10949の修正は必須だったという事です。

了解です。解説ありがとうございます。

**Comment by nmaya** [comment]
> データが欠けてRDPサーバー側で復号出来なくなって切られていると思います。
> あと、SCP送信でデータが欠けます。

コメントがあるのは SSH2_send_channel_data(), SSH2_channel_input_eof(), SSH_open_channel() と、いずれも送信部でした。

また、Rekey 中の受信データについては、このような問題は起こらないでしょうか？

> 別Issueを立てて対応した方がいいかもしれません。

「Rekey自体」と「Rekey中のデータ通信」なので別にするのがいいと思います。

ところで、この問題（Rekey中のデータ通信）の修正は 5.0, 4.107 に入れられそうでしょうか？

**Comment by ttdoda** [comment]
> また、Rekey 中の受信データについては、このような問題は起こらないでしょうか？

Rekey中にはデータパケットは送られて来ないので大丈夫です。

> ところで、この問題（Rekey中のデータ通信）の修正は 5.0, 4.107 に入れられそうでしょうか？

完全た対処はちょっと時間がかかりそうですが、ほとんどのケースを占める SSH2_send_channel_data() への対処はすぐにできるように思います。

**Comment by nmaya** [comment]
## 対応

SSH2 の Rekey 時に SSH_MSG_NEWKEYS が送信されない問題を修正（本件）

- trunk
  - r10943
- 4-stable
  - r10944

Rekey の時にも ext-info-c を送信する問題を修正（[#36111](https://osdn.net/projects/ttssh2/ticket/36111)）

- trunk
  - r10949, r10955
- 4-stable
  - r10956
