### ISSUE TITLE
クリッカブルURLが無効でもURLのマウスオーバーでマウスポインタが変わる

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/osdn-download#9]
[設定]-[その他の設定]-[全般]の[クリッカブルURLを有効にする]のチェックボックスがoffの状態でもURL文字列のマウスオーバー時にマウスポインタの形状が変わる。
マウスポインタの形状が変わると何か動作が変わるように見えてしまうので、クリッカブルURLが無効の時は変わらないようにするのが望ましいと思われる。

## バージョン
4.106, 4.107 RC2, 5.0 RCで再現。

**Comment by ttdoda** [comment]
URL文字列の特殊扱い関連では、他に

  * URL属性色
  * URL下線表示

が有るが、マウスポインタの形状変化を行うかはクリッカブルURL設定に合わせるのが妥当だと思う。

**Comment by nmaya** [comment]
はい、いいと思います。

こうすればいいですか？別の箇所でも考慮が必要ですか？
```
Index: vtwin.cpp
===================================================================
--- vtwin.cpp	(revision 10938)
+++ vtwin.cpp	(working copy)
@@ -2122,7 +2122,7 @@
 		mousereport = MouseReport(IdMouseEventMove, 0, point.x, point.y);
 
 	if (! (LButton || MButton || RButton)) {
-		if (BuffCheckMouseOnURL(point.x, point.y))
+		if (BuffCheckMouseOnURL(point.x, point.y) && ts.EnableClickableUrl)
 			SetMouseCursor("HAND");
 		else
 			SetMouseCursor(ts.MouseCursorName);
```

**Comment by ttdoda** [comment]
はい。マウスポインタの形状の問題だけなので、そこだけで大丈夫だと思います。

**Comment by nmaya** [comment]
修正しました。
- trunk: [r10941](https://osdn.net/projects/ttssh2/scm/svn/commits/10941)
- 4-stable: [r10942](https://osdn.net/projects/ttssh2/scm/svn/commits/10942)
